package com.enderville.mod.asm;


/**
 * GoreCoreModContainer.java
 * 
 * GoreCore
 *
 * @author DylanGore (http://github.com/DylanGore)
 * @license LGPL v3 (https://github.com/EnderVille/EnderVilleMod/blob/master/LICENSE)
 * 
 */

//public class EnderVilleModContainer extends DummyModContainer {
//	
//	public EnderVilleModContainer()
//	  {
//	    super(new ModMetadata());
//	    ModMetadata md = super.getMetadata();
//	    md.authorList = Arrays.asList(new String[] { "DylanGore" });
//	    md.version = "@VERSION@";
//	    md.name = "EnderVille|Core";
//	    md.modId = "EnderVille|Core";
//	    md.autogenerated = false;
//	    md.description = "";
//	    md.useDependencyInformation = false;
//	    md.url = "http://dylangore.info/enderville-mod";
//	    md.credits = "Code by DylanGore";
//	  }
//	
//	public boolean registerBus(EventBus bus, LoadController controller) {
//        bus.register(this);
//        return true;
//        }
//}
